<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_IQAC</name>
   <tag></tag>
   <elementGuidId>0084a343-d34e-4dd9-ae6e-a44050cf6013</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='smoothmenu1']/ul/li[6]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li:nth-of-type(6) > a.selected</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;IQAC&quot;s]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>bd7cadc2-dc80-4753-9633-be9fdf78829e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>selected</value>
      <webElementGuid>e666212f-7a7f-4861-a39a-c7bdca4d5762</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>IQAC</value>
      <webElementGuid>e36dc4c9-0d79-4ab3-8cb4-95c4001f75f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;smoothmenu1&quot;)/ul[1]/li[6]/a[@class=&quot;selected&quot;]</value>
      <webElementGuid>bb96b1c3-8530-43db-802f-72ea4ac47231</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='smoothmenu1']/ul/li[6]/a</value>
      <webElementGuid>cf4584a4-2cbd-4e97-82ef-75edcb5d285a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'IQAC')]</value>
      <webElementGuid>95c71816-2816-49fc-8d7c-dca039973ff1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Physical Education'])[1]/following::a[1]</value>
      <webElementGuid>b8da5f15-3312-4be1-be7b-f3762b05f3fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Geography'])[1]/following::a[2]</value>
      <webElementGuid>0d81af07-5964-4c47-b057-d8ec49e7274b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='IQAC Reports'])[1]/preceding::a[1]</value>
      <webElementGuid>948d9269-ea2a-4200-ac06-23d167b31d40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Staff - Sactioned'])[1]/preceding::a[2]</value>
      <webElementGuid>5e7e7350-c4a0-4850-8a86-38c486491cdb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='IQAC']/parent::*</value>
      <webElementGuid>7b19bbda-88c0-4885-a52f-f541f6faf779</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '')])[32]</value>
      <webElementGuid>1105dac7-9272-4dcf-a2c6-435c717284f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[6]/a</value>
      <webElementGuid>072a547a-f8ef-4205-801e-ef75dd2a2854</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = 'IQAC' or . = 'IQAC')]</value>
      <webElementGuid>ba745c5b-7b23-4db1-83a1-7249d669f0b6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
