<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Vice-Chancellor</name>
   <tag></tag>
   <elementGuidId>257ac02b-f306-4b1c-9085-62cecafc432a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//a[contains(text(),'Vice-Chancellor')])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li.dropdown.mega-dropdown.open > ul.dropdown-menu.mega-dropdown-menu.row > li.col-sm-3 > ul > li:nth-of-type(2) > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Vice-Chancellor&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>16401443-0562-4103-ad25-1c3b9f0d4e5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>Administration/vc</value>
      <webElementGuid>f1ec3917-7f13-4041-a662-55b6e918cfd6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Vice-Chancellor</value>
      <webElementGuid>c4f58442-329e-4f2c-af94-6f3482b30dd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;navbar navbar-fixed-top navbar-default&quot;]/div[@class=&quot;navbar&quot;]/div[@class=&quot;collapse navbar-collapse js-navbar-collapse&quot;]/ul[@class=&quot;nav navbar-nav&quot;]/li[@class=&quot;dropdown mega-dropdown open&quot;]/ul[@class=&quot;dropdown-menu mega-dropdown-menu row&quot;]/li[@class=&quot;col-sm-3&quot;]/ul[1]/li[2]/a[1]</value>
      <webElementGuid>6a4261e3-1abc-4f43-b089-34507714aadc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Vice-Chancellor')])[2]</value>
      <webElementGuid>d4c82754-5b5a-45a4-a615-766802617b48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Administration'])[3]/following::a[1]</value>
      <webElementGuid>7a7560f1-88db-459a-9162-31ac98be771e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Administration'])[2]/following::a[1]</value>
      <webElementGuid>6808b473-90d0-4879-bc8f-ff1efc896218</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Registrar'])[1]/preceding::a[1]</value>
      <webElementGuid>f91560b7-8628-422d-b2e0-635b4f7fb697</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Controller of Examinations'])[1]/preceding::a[2]</value>
      <webElementGuid>bfb43a37-cb9b-4436-9d51-de44bca59a7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'Administration/vc')]</value>
      <webElementGuid>4b7754bb-7cf8-4a8c-ae50-bfab3420cb54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ul[3]/li/ul/li[2]/ul/li[2]/a</value>
      <webElementGuid>4a606c1a-acb0-4ace-ab4b-24b59fc2532c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'Administration/vc' and (text() = 'Vice-Chancellor' or . = 'Vice-Chancellor')]</value>
      <webElementGuid>b3967d8a-80d3-43f9-996f-ca599a6b93de</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
